### ISSUE TITLE
[Docs] Add metadata to GridMap

### ISSUE THREAD

**Issue by FisherTiger95** [AlexeyBond/godot-constraint-solving#10]
I am encountering difficulties using `WFC2DPreconditionDungeon` with the GridMap demo. Specifically, I am unsure how to set metadata for grid tiles, such as "wfc_dungeon_road" and "wfc_dungeon_wall." I have attempted various combinations, including setting the metadata for each MeshInstance3D within the library-source, but have been unsuccessful in retrieving the metadata in the code (the `assert(not passable_domain.is_empty())` in `/wfc/problems/2d/preconditions/precondition_2d_dungeon.gd` always fails).

Is it possible to use `WFC2DPreconditionDungeon` with gridmap?
How can I set the metadata in my grid tiles?

Suppose that I want to add `WFC2DPreconditionDungeon` with the gridmap demo, what are the steps that I should follow to set the "wfc_dungeon_road" and "wfc_dungeon_wall" metadata to the mesh?

Am I supposed to set metadata for each MeshInstance3D inside the library-source?

I can contribute by adding some documentation regarding that part when everything will be more clear.

**Comment by AlexeyBond** [comment]
Hi.

I believed that there is a way to set metadata for meshes in mesh library. But now, after some research, it looks like I was wrong and it isn't actually possible 🤦‍♂️.

I will add a way to specify metadata for meshes in mapper settings and/or different way to specify tile classes for dungeon generator.

**Comment by AlexeyBond** [comment]
I've added everything necessary to use dungeon generator with grid maps in master branch. Examples are there as well.

**Comment by AlexeyBond** [comment]
Support for 2d WFC with dungeon precondition on GridMaps is added in release [1.4](https://github.com/AlexeyBond/godot-constraint-solving/releases/tag/1.4). Now there are two ways to do it:
- using metadata settings in mapper. See https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/examples/demo_wfc_2d_gridmap_dungeon_mapper_meta.tscn
- using a separate map. See https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/examples/demo_wfc_2d_gridmap_dungeon_class_map.tscn
