### ISSUE TITLE
"Supports different node types: GridMap"

### ISSUE THREAD

**Issue by stesproject** [AlexeyBond/godot-constraint-solving#19]
and then:
"What's not (yet) implemented:
    3d map generation. Generation of 3d maps (for GridMaps or multi-layered TileMaps) is not yet implemented."

So... it does not support GridMap.

Do you have an idea of ​​when it will be supported?

**Comment by AlexeyBond** [comment]
GridMaps are supported, but a 2D slice of a map can only be generated, see `demo_wfc_2d_gridmap*` [examples](https://github.com/AlexeyBond/godot-constraint-solving/tree/master/addons/wfc/examples).

Multi-layered tilemaps are supported as well, however, it works with 2D grid, treating every combination of tiles on different layers as a single tile. With a true 3D generator it would be possible to trat a layer index as third coordinate.

Perhaps, it's worth clarifying this in readme.

For true 3D generator - I'm not sure when will I implement it. A dynamic/lazy generation most likely will be the next feature I will work on and I have yet no idea how long it will take.

But I do accept PRs :)
