### ISSUE TITLE
Propose a way to simplify sample map creation

### ISSUE THREAD

**Issue by shanayyy** [AlexeyBond/godot-constraint-solving#24]
Thanks for your amazing work, this will definitely save people a lot of time.😃

The sample map is easy to use, but it is difficult to configure on some of the more complex tilesets, such as this one:
<img src="https://github.com/user-attachments/assets/394ec716-6623-471e-9db8-34ddc0a4fed2" width="256">
[Asset link](https://www.kenney.nl/assets/pixel-shmup)

To generate roads and rivers, quite a bit of configuration is required here. 
I know there is a `complete_matrices` option, but if there is a bad sample configuration, it is hard to see what is missed, so I just do it all manually. 
This is just a small sample and I may have missed many：
<img width="512" alt="image" src="https://github.com/user-attachments/assets/77834766-6255-419b-8485-6316419f794d">

It can be seen that configuring a complete rule sample requires a lot of work and is difficult to track. 
So I propose that the rules can be generated from the terrain set of TileSet.
https://docs.godotengine.org/en/stable/tutorials/2d/using_tilesets.html#creating-terrain-sets-autotiling

Each tile has a terrain, and has saved the terrains it can be adjacent to, so I think there is enough information to generate rules.
If this is implemented, most configurations of the sample map should be avoided. 
What do you think?

**Comment by AlexeyBond** [comment]
That sounds like a good idea, at least at first glance. So, thanks for the suggestion.

I didn't yet use terrains, and thus couldn't see that this feature can be used this way. In fact it looks like a very minimal and limited version of wave function collapse runs when you draw tilemap in terrain mode.

One issue I can see for now is - it isn't obvious how it should work with multi-layer maps. Especially if multiple layers do have terrain tiles.

<details>
<summary>offtopic</summary>
<blockquote>if there is a bad sample configuration, it is hard to see what is missed</blockquote>

I do have some ideas on how to make more useful error reporting (mostly highlighting tiles that do not have any possible neighbours).. but that will require some amount of work and some workflow changes, so it won't be done soon.
</details>

**Comment by shanayyy** [comment]
Hi, I tried implementing my idea and this is the result:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/d6b3b0cb-dd08-4e9c-88bd-ed0048db3c5b">
Some noise is used to configure precondition.

And this is the sample map:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/75017f03-1655-48bf-8f5e-bd5b08f97c54">
There is no need to configure anything other than putting the required tiles in.

**Comment by AlexeyBond** [comment]
That looks nice!

Will you be able to share the code (create a PR or show an example project)?

**Comment by shanayyy** [comment]
Of course, I uploaded a demo, you can run the main scene to see the result, the modified code is actually quite small, I have opened it in the editor, so you should be able to see it in the script view when you open the project.
[example.zip](https://github.com/user-attachments/files/16600503/example.zip)

**Comment by shanayyy** [comment]
Update:
I tried adding these two lines of code to generate a tileable map.
<img width="512" alt="image" src="https://github.com/user-attachments/assets/89685995-a59c-4f23-a6bc-36b5e8a0cf86">
here is the example, The map is repeated to show seamless tiling:

https://github.com/user-attachments/assets/8ab2cce9-4f08-47fe-a015-6ffefae18d1d

But I can only get the correct result without using multithreading.

**Comment by AlexeyBond** [comment]
> But I can only get the correct result without using multithreading.

When multithreading is enabled, a problem is split into few smaller problems, with smaller rects, so in your case, I guess, each of those small problems wraps coordinates within it's own small rect instead of the big one.

**Comment by AlexeyBond** [comment]
Implemented in [v1.7](https://github.com/AlexeyBond/godot-constraint-solving/releases/tag/1.7)
