### ISSUE TITLE
Arbitrary 2d array data instead of TileMap?

### ISSUE THREAD

**Issue by shazzner** [AlexeyBond/godot-constraint-solving#28]
Hello, I'm working on a 3d puzzle game involving blocks of different types. I'd like to setup a feature that generates a random puzzle based on predefined rules, naturally I found WFC. Most implementations though center around generating TileMap data and in looking at this project's docs it looks like you need a source and target tilemap.

Instead of building shims and translating tilemap data to data that I can use for my game logic, I'm wondering if I can simply pass in a 2d array of constraints (consisting of int values), along with target dimensions and it would solve that.

I saw that you have a sodoku solver, but my case is a bit simpler and I didn't see this specific example. Thanks!

**Comment by AlexeyBond** [comment]
Hi.

This addon does not require `TileMap` or any other specific node. Instead it uses [mappers](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d.gd) to interface between the algorithm and nodes. So if you do have some sort of map-like node in your game, you can implement a mapper for that node type.

If you don't have such nodes and really want to work with just arrays, then it gets more complicated, as WFC-specific part of the addon is built with assumption that there is some sort of map node. You'll have to
- write a custom [`WFCProblem`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/problem.gd), perhaps, most of [`WFC2DProblem`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/problem_wfc_2d.gd) can be reused, except for map-related logic
- create and use a problem and solver manually in your code, like it's done in the sudoku example
