### ISSUE TITLE
Cannot seem to find WFC2DGenerator node

### ISSUE THREAD

**Issue by notbaldie** [AlexeyBond/godot-constraint-solving#3]
Hi, as the title mentions, I am trying to follow the how-to: https://github.com/AlexeyBond/godot-constraint-solving#how-to-use but I can't seem to get the WFC2DGenerator node to appear in my node search window. I'm not sure if I need to do something more after installing the plugin or not.

Any advice?

**Comment by AlexeyBond** [comment]
Hi. In order for a plugin to work, it should be enabled in project settings: https://docs.godotengine.org/en/stable/tutorials/plugins/editor/installing_plugins.html#enabling-a-plugin. Maybe that's the problem.

**Comment by notbaldie** [comment]
I see, you are definitely right. I thought that plugins may get enabled by default. I was wrong, that was it, thank you for the quick help!
